# Generated by Django 4.1.5 on 2023-01-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='campus',
            new_name='campus_id',
        ),
    ]
